export const translations = {
  ru: {
    loginTitle: "Вход в личный кабинет",
    loginLabel: "Логин",
    loginPlaceholder: "Введите ваш логин",
    passwordLabel: "Пароль",
    passwordPlaceholder: "Введите ваш пароль",
    rememberMe: "Запомнить меня",
    forgotPassword: "Забыли пароль?",
    loginButton: "Войти",
    noAccount: "Нет аккаунта?",
    register: "Регистрация",
    loginSuccess: "Успешный вход!",
    loginError: "Неверный логин или пароль",
    welcome: "Добро пожаловать",
    dashboardTitle: "Панель управления",
    terminals: "Терминалы",
    terminalsStatus: "5 онлайн / 7 всего",
    monitoring: "Мониторинг",
    monitoringStatus: "Все системы в норме",
    finances: "Финансы",
    balance: "Баланс: 1,234.56 ₽",
    events: "События",
    eventsStatus: "Нет новых событий",
    logout: "Выйти",
  },
  en: {
    loginTitle: "Account Login",
    loginLabel: "Login",
    loginPlaceholder: "Enter your login",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    loginButton: "Log In",
    noAccount: "No account?",
    register: "Register",
    loginSuccess: "Login successful!",
    loginError: "Invalid login or password",
    welcome: "Welcome",
    dashboardTitle: "Dashboard",
    terminals: "Terminals",
    terminalsStatus: "5 online / 7 total",
    monitoring: "Monitoring",
    monitoringStatus: "All systems operational",
    finances: "Finances",
    balance: "Balance: $1,234.56",
    events: "Events",
    eventsStatus: "No new events",
    logout: "Logout",
  },
};